--- 
services: 
  redis: 
    networks:
      - redis-network
    command: 
      - redis-server
      - "--appendonly"
      - "yes"
    image: redis
    ports: 
      - "6379:6379"

  contact: 
    networks:
      - api-network
      - redis-network
    build: .
    command: npm start
    environment:
      - NODE_ENV=development
    depends_on: 
      - redis
    ports: 
      - "3000:3000"
    restart: always
    volumes:
      - /var/www/api/node_modules

networks:
  api-network:
    driver: bridge
  redis-network:
    driver: bridge

volumes:

version: "3.7"
